x-common_environment: &common_environment
  EBIKES_SERVICE_ADDRESS: ebikes:8080
  USERS_SERVICE_ADDRESS: users:8080
  RIDES_SERVICE_ADDRESS: rides:8080

x-common_healthcheck: &common_healthcheck
  healthcheck:
    test: curl --fail localhost:8080/healthCheck || exit 1
    start_period: 20s
    start_interval: 1s
    interval: 60s
    timeout: 5s
    retries: 2
  restart: unless-stopped
  
services:
  ebikes:
    build:
      args:
        - executable=EBikes/executable.jar
    networks:
      - private_network
    environment:
      <<: *common_environment
    <<: *common_healthcheck

  users:
    build:
      args:
        - executable=Users/executable.jar
    networks:
      - private_network
    environment:
      <<: *common_environment
    depends_on:
      users-es:
        condition: service_healthy
    <<: *common_healthcheck
  users-es:
    image: apache/kafka:3.9.0
    networks:
      - private_network
    environment: # https://hub.docker.com/r/apache/kafka Overriding one variable makes every other unset so you need to set them to default values
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://users-es:9092,CONTROLLER://localhost:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://users-es:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@localhost:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_NUM_PARTITIONS: 3
    healthcheck:
      test: /opt/kafka/bin/kafka-cluster.sh cluster-id --bootstrap-server users-es:9092 || exit 1
      interval: 1s
      timeout: 60s
      retries: 60

  rides:
    build:
      args:
        - executable=Rides/executable.jar
    networks:
      - private_network
    environment:
      <<: *common_environment
    <<: *common_healthcheck

networks:
  private_network:
    driver: bridge
