x-restart_policy: &restart_policy
  restart: ${RESTART_POLICY?}

services:
  ebikes:
    ports:
      - 8081:8080
    <<: *restart_policy

  users:
    ports:
      - 8082:8080
    <<: *restart_policy

  rides:
    ports:
      - 8083:8080
    <<: *restart_policy

  smart-city:
    ports:
      - 8084:8080
    <<: *restart_policy
