x-restart_policy: &restart_policy
  restart: ${RESTART_POLICY?}

services:
  ebikes:
    volumes:
      - ${HOME}/Desktop/EBikeApp/db:/data/db:rw
    ports:
      - 8081:8080
    <<: *restart_policy

  users:
    volumes:
      - ${HOME}/Desktop/EBikeApp/db:/data/db:rw
    ports:
      - 8082:8080
    <<: *restart_policy

  rides:
    volumes:
      - ${HOME}/Desktop/EBikeApp/db:/data/db:rw
    ports:
      - 8083:8080
    <<: *restart_policy
