x-restart_policy: &restart_policy
  restart: ${RESTART_POLICY?}

services:
  ebikes:
    ports:
      - 30001:8080
    <<: *restart_policy

  users:
    ports:
      - 30002:8080
    <<: *restart_policy

  rides:
    ports:
      - 30003:8080
    <<: *restart_policy

  smart-city:
    ports:
      - 30004:8080
    <<: *restart_policy
