@startuml components

left to right direction

component "User frontend" as UserFE <<Client>>
component "Admin frontend" as AdminFE <<Client>>
component "ABike" <<Client>>

component "Smart city" <<Microservice>> as SmartCity
interface "Smart city REST API" as SmartCityAPI
SmartCity -u-() SmartCityAPI

component Backend <<Server>> {

    component "EBikes" <<Microservice>> as EBikes
    interface "EBikes REST API" as EBikesAPI
    EBikes --u--() EBikesAPI
    interface "EBikes events" <<Event Stream>> as EBikesES
    EBikes -u-() EBikesES
    
    component "Users" <<Microservice>> as Users
    interface "Users REST API" as UsersAPI
    Users --u--() UsersAPI
    interface "Users events" <<Event Stream>> as UsersES
    Users -u-() UsersES

    component "Rides" <<Microservice>> as Rides
    interface "Rides REST API" as RidesAPI
    Rides -u-() RidesAPI
    interface "Rides events" <<Event Stream>> as RidesES
    Rides --() RidesES
    Rides --( UsersES
    Rides --( EBikesES

    EBikes -l-( RidesES
}

UserFE --( RidesAPI
UserFE --( UsersAPI
UserFE --( EBikesAPI
UserFE --( SmartCityAPI
AdminFE --( RidesAPI
AdminFE --( UsersAPI
AdminFE --( EBikesAPI
AdminFE --( SmartCityAPI
ABike ---( RidesAPI
ABike ---( EBikesAPI
ABike ---( SmartCityAPI

@enduml