@startuml ebikes-components

title "EBikes microservice"

left to right direction

component EventStore
interface "EBikes API" as EBikesAPI

hexagon Adapters {
    hexagon Domain as DomainHex {
        component Domain {
            portout EBikesEventStore
            portin EBikesService
        }
    }

    component "EventStoreAdapter" as EventStoreAdapter
    EventStoreAdapter -u-|> EBikesEventStore
    EventStoreAdapter -l-> EventStore

    component "HTTPPresentationAdapter" as HTTPAdapter
    HTTPAdapter -d-> EBikesService
    HTTPAdapter -l-() EBikesAPI
}

@enduml
