@startuml ebikes-components

title "EBikes microservice"

left to right direction

component "DB"
interface "EBikes API" as EBikesAPI
interface "Collect Metrics API" as CollectMetricsAPI

hexagon Adapters {
    hexagon Domain as DomainHex {
        component Domain {
            portout "EBikesRepository" as Repo
            portout MetricsService
            portin EBikesService
        }
    }

    component "Repository Adapter" as RepoAdapter
    RepoAdapter -u-|> Repo
    RepoAdapter -l-> DB

    component MetricsAdapter
    MetricsAdapter -u-|> MetricsService
    MetricsAdapter -r-( CollectMetricsAPI

    component "HTTPPresentationAdapter" as HTTPAdapter
    HTTPAdapter -d-> EBikesService
    HTTPAdapter -l-() EBikesAPI
}

component "Metrics" as Metrics <<Microservice>>
Metrics -r-() CollectMetricsAPI

@enduml
