@startuml streets-graph


(J1) -- (J2) : "S1"
(J1) -- (J3) : "S2"
(J1) -- (J5) : "S3"

(J3) -- (J2) : "S4"
(J3) -- (J4) : "S5"

(J5) -- (J4) : "S6"

note left of (J1)
    Charging station
end note

note as N
    Every junction J<N> (except J1)
    has a semaphore SEM<N>
end note

@enduml
