@startuml use-cases

actor "User"
actor "System Administrator" as Admin

left to right direction

rectangle "EBike App" {
    User --> (Go on a ride)

    Admin -u-> (Monitor bike positions)
    Admin -u-> (Monitor rides)
    Admin -u-> (See registered users)
    Admin -u-> (Register new bike)
}

@enduml