@startuml users-components

title "Users microservice"

left to right direction

component "DB"
interface "Users API" as UsersAPI
interface "Users Registration API" as UsersRegistrationAPI

hexagon Adapters {
    hexagon Domain as DomainHex {
        component Domain {
            portout "UsersRepository" as Repo
            portin UsersService
        }
    }

    component "Repository Adapter" as RepoAdapter
    RepoAdapter -u-|> Repo
    RepoAdapter -l-> DB

    component "HTTPPresentationAdapter" as HTTPAdapter
    HTTPAdapter -d-> UsersService
    HTTPAdapter -() UsersAPI
    HTTPAdapter -() UsersRegistrationAPI
    ' just for layout
    UsersAPI -[hidden]-> UsersRegistrationAPI
}

@enduml
