@startuml users-components

title "Users microservice"

left to right direction

component "EventStore"
interface "Users API" as UsersAPI

hexagon Adapters {
    hexagon Domain as DomainHex {
        component Domain {
            portout UsersEventStore
            portin UsersService
        }
    }

    component "EventStoreAdapter" as EventStoreAdapter
    EventStoreAdapter -u-|> UsersEventStore
    EventStoreAdapter -l-> EventStore

    component "HTTPPresentationAdapter" as HTTPAdapter
    HTTPAdapter -d-> UsersService
    HTTPAdapter -l-() UsersAPI
}

@enduml
