apiVersion: apps/v1
kind: Deployment
metadata:
  name: ebikes
spec:
  replicas: 3
  selector:
    matchLabels:
      name: ebikes
  template:
    metadata:
      labels:
        name: ebikes
    spec:
      containers:
        - name: ebikes
          image: ventus218/sap-assignment-03-ebikes
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: environment
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /healthCheck
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 10
            timeoutSeconds: 10
            failureThreshold: 2

---
apiVersion: v1
kind: Service
metadata:
  name: ebikes
spec:
  selector:
    name: ebikes
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30001
  sessionAffinity: ClientIP
