apiVersion: v1
kind: ConfigMap
metadata:
  name: environment
data:
  EBIKES_SERVICE_ADDRESS: ebikes:8080
  USERS_SERVICE_ADDRESS: users:8080
  RIDES_SERVICE_ADDRESS: rides:8080
  SMARTCITY_SERVICE_ADDRESS: smart-city:8080
  KAFKA_SERVICE_ADDRESS: kafka:9092
