apiVersion: v1
kind: Pod
metadata:
  name: smart-city
  labels:
    name: smart-city
spec:
  containers:
    - name: smart-city
      image: sap-assignment-03-smart-city
      imagePullPolicy: IfNotPresent
      envFrom:
        - configMapRef:
            name: environment
      ports:
        - containerPort: 8080
      livenessProbe:
        httpGet:
          path: /healthCheck
          port: 8080
        initialDelaySeconds: 20
        periodSeconds: 60
        timeoutSeconds: 5
        failureThreshold: 2

---
apiVersion: v1
kind: Service
metadata:
  name: smart-city
spec:
  selector:
    name: smart-city
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30004
