apiVersion: apps/v1
kind: Deployment
metadata:
  name: users
spec:
  replicas: 1
  selector:
    matchLabels:
      name: users
  template:
    metadata:
      labels:
        name: users
    spec:
      containers:
        - name: users
          image: sap-assignment-03-users
          imagePullPolicy: IfNotPresent
          env:
            - name: KAFKA_SERVICE_ADDRESS
              value: kafka:9092
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: users
spec:
  selector:
    name: users
  ports:
    - protocol: TCP
      port: 8080
