apiVersion: apps/v1
kind: Deployment
metadata:
  name: users
spec:
  replicas: 3
  selector:
    matchLabels:
      name: users
  template:
    metadata:
      labels:
        name: users
    spec:
      containers:
        - name: users
          image: ventus218/sap-assignment-03-users
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: environment
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /healthCheck
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 60
            timeoutSeconds: 5
            failureThreshold: 2

---
apiVersion: v1
kind: Service
metadata:
  name: users
spec:
  selector:
    name: users
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30002
  sessionAffinity: ClientIP
