openapi: 3.0.3
info:
  title: Users Service API
  version: 1.0.0
  description: API for managing users and performing health checks.
paths:
  /users:
    get:
      description: Retrieve a list of all registered users.
      responses:
        '200':
          description: A list of registered users.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/User'

    post:
      description: Register a new user.
      requestBody:
        description: The username of the user to register.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Username'
      responses:
        '200':
          description: The user was successfully registered.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '409':
          description: Username already in use.
          content:
            text/plain:
              schema:
                type: string

  /healthCheck:
    get:
      description: Perform a health check to verify the service is operational.
      responses:
        '200':
          description: The service is healthy.
          content:
            text/plain:
              schema:
                type: string
        '503':
          description: Service unavailable.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HealthCheckError'

components:
  schemas:
    Username:
      type: object
      description: Represents a user's username.
      properties:
        value:
          type: string
          description: The username of the user.
      required:
        - value

    User:
      type: object
      description: Represents a user and their associated data.
      properties:
        username:
          $ref: '#/components/schemas/Username'
      required:
        - username

    HealthCheckError:
      type: object
      description: Represents an error encountered during a health check.
      properties:
        error:
          type: string
          description: A description of the health check error.
      required:
        - error
